$(document).ready(function () {indexDict['en'] = [{ "title" : "Getting Started ", 
"url" : "getting-started.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Getting Started ", 
"snippet" : "Welcome to the Tonkean Documentation Portal! We’re glad you’re here. Here you'll find information on how to use Tonkean to orchestrate processes across various business functions while remaining secure and fully integrated with your tech stack. In the Documentation Portal, we take you from the most ...", 
"body" : "Welcome to the Tonkean Documentation Portal! We’re glad you’re here. Here you'll find information on how to use Tonkean to orchestrate processes across various business functions while remaining secure and fully integrated with your tech stack. In the Documentation Portal, we take you from the most basic concepts that underly Tonkean as a no-code platform, through how to build and maintain your own workflows, and even to some advanced use cases—all without writing a single line of code. If you're a new maker just getting started on your Tonkean journey, see the  Quick Start Guide , where you can learn basic Tonkean concepts and build your first Solution. If you're already an experienced user, see either the  Maker Playbook  or  Admin Playbook  for how-to guides, configuration information, and other content. " }, 
{ "title" : "Navigate Tonkean ", 
"url" : "getting-started/navigate-tonkean.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Getting Started \/ Navigate Tonkean ", 
"snippet" : "H1 Log In To log in to Tonkean, navigate to track.tonkean.com\/login and select one of the available SSO options or enter your work email to generate a login email. If instead you received a login token via email, select \"I've got the code\" at the bottom of the screen and enter the token there. H1 Na...", 
"body" : "H1 Log In To log in to Tonkean, navigate to track.tonkean.com\/login and select one of the available SSO options or enter your work email to generate a login email. If instead you received a login token via email, select \"I've got the code\" at the bottom of the screen and enter the token there. H1 Navigate Tonkean When you first log in to Tonkean, you'll see the Tonkean Boards screen, containing all of the boards you have access to. For most users, this will only be one or two boards, while other users may have many. Select the board you would like to work in to get started. Selecting a board opens the Solutions Studio, one of the four main screens in Tonkean. From any of these screens, select the grid icon, , in the top left corner to navigate to any of the four main screens: " }, 
{ "title" : "Quick Start Guide ", 
"url" : "getting-started/quick-start-guide.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Getting Started \/ Quick Start Guide ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "What is Tonkean? ", 
"url" : "getting-started/quick-start-guide/what-is-tonkean-.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Getting Started \/ Quick Start Guide \/ What is Tonkean? ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "What are Modules? ", 
"url" : "getting-started/quick-start-guide/what-are-modules-.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Getting Started \/ Quick Start Guide \/ What are Modules? ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "What are Business Reports? ", 
"url" : "getting-started/quick-start-guide/what-are-business-reports-.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Getting Started \/ Quick Start Guide \/ What are Business Reports? ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Build Your First Solution ", 
"url" : "getting-started/quick-start-guide/build-your-first-solution.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Getting Started \/ Quick Start Guide \/ Build Your First Solution ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Maker Playbook ", 
"url" : "maker-playbook.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Maker Playbook ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Admin Playbook ", 
"url" : "admin-playbook.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Admin Playbook ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Business Reports and Metrics ", 
"url" : "business-reports-and-metrics.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Business Reports and Metrics ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Runtime Jobs ", 
"url" : "runtime-jobs.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Runtime Jobs ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Release Notes ", 
"url" : "release-notes.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Release Notes ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Resources ", 
"url" : "resources.html", 
"breadcrumbs" : "Tonkean Documentation Portal \/ Resources ", 
"snippet" : "...", 
"body" : "" }
]
$(document).trigger('search.ready');
});